---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

# Setup qemu-kvm nested virtualization
# This is the hypervisor used in our tests.
- name: Install qemu-kvm
  package:
    name: "qemu-kvm"
    state: "present"
  retries: "3"
  delay: "20"

# Grab CPU flags from "/proc/cpuinfo" and put the result into the
# "cpu_flags_cmd" variable.
- name: Get cpu flags
  command: |
    awk -F: '/^flags/ {print $2; exit}' /proc/cpuinfo
  register: cpu_flags_cmd
  changed_when: false

# Extract the flags into a list variable named "cpu_flags".
- name: Set cpu flags fact
  set_fact:
    cpu_flags: "{{ cpu_flags_cmd.stdout.split() }}"

- block:
    - name: Unload kvm_intel module
      modprobe:
        name: "kvm_intel"
        state: "absent"

    - name: Configure KVM module with Intel nested virtualization support
      copy:
        dest: "/etc/modprobe.d/kvm_intel.conf"
        content: |
          options kvm_intel nested=1

    - name: Re-load kvm_intel module
      modprobe:
        name: "kvm_intel"
        state: "present"
      register: nested_virtualization

    - name: Ensure nested virtualization is enabled
      command: cat /sys/module/kvm_intel/parameters/nested
      register: nested_virtualization
      failed_when: ('FAILED' in nested_virtualization.stderr) or
                   ('N' in nested_virtualization.stdout)

    - debug:
        msg: >
          /sys/module/kvm_intel/parameters/nested:
          {{ nested_virtualization.stdout }}

    - name: Configure kvm hypervisor if running nested virtualization
      lineinfile:
        line: "{{ item }}"
        state: "present"
        insertafter: "EOF"
        dest: "{{ clone_path }}/hiera/common.yaml"
      with_items:
        - "openstack_integration::nova::libvirt_virt_type: kvm"
        - "openstack_integration::nova::libvirt_cpu_mode: host-model"
  when:
    - "{{ 'Intel' in ansible_processor |join('') }}"
    - "{{ 'vmx' in cpu_flags }}"

- block:
    - name: Unload kvm_amd module
      modprobe:
        name: "kvm_amd"
        state: "absent"

    - name: Configure KVM module with AMD nested virtualization support
      copy:
        dest: "/etc/modprobe.d/kvm_amd.conf"
        content: |
          options kvm_amd nested=1

    - name: Re-load kvm_amd module
      modprobe:
        name: "kvm_amd"
        state: "present"
      register: nested_virtualization

    - name: Ensure nested virtualization is enabled
      command: cat /sys/module/kvm_amd/parameters/nested
      register: nested_virtualization
      failed_when: ('FAILED' in nested_virtualization.stderr) or
                   ('0' in nested_virtualization.stdout)

    - debug:
        msg: >
          /sys/module/kvm_amd/parameters/nested:
          {{ nested_virtualization.stdout }}

    - name: Configure kvm hypervisor if running nested virtualization
      lineinfile:
        line: "{{ item }}"
        state: "present"
        insertafter: "EOF"
        dest: "{{ clone_path }}/hiera/common.yaml"
      with_items:
        - "openstack_integration::nova::libvirt_virt_type: kvm"
        - "openstack_integration::nova::libvirt_cpu_mode: host-model"
  when:
    - "{{ 'AMD' in ansible_processor |join('') }}"
    - "{{ 'svm' in cpu_flags }}"
