---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- block:
    - name: Setup delorean repository
      get_url:
        url: "{{ delorean_url }}"
        dest: "/etc/yum.repos.d/delorean.repo"
        mode: "0644"

    - name: Setup delorean-deps repository
      get_url:
        url: "{{ delorean_deps_url }}"
        dest: "/etc/yum.repos.d/delorean-deps.repo"
        mode: "0644"

    # scenario001 installs Ceph with puppet-ceph's ceph::repo
    # Let's setup the latest release to try and catch problems ahead of them
    # Ceph also requires EPEL for, amongst other things, leveldb-devel.
    - name: Enable EPEL
      yum:
        name: "epel-release"
        state: "present"
      retries: "3"
      delay: "20"

    - name: Setup ceph.com signing key
      rpm_key:
        state: "present"
        key: "https://download.ceph.com/keys/release.asc"
      when: test == "scenario001"

    - name: Setup ceph.com repositories
      template:
        src: "templates/ceph.repo.j2"
        dest: "/etc/yum.repos.d/ceph.repo"
      when: test == "scenario001"
  vars:
    task: "tasks/repositories.yml"
  rescue:
    - name: Failure occurred, executing rescue
      include: roles/common/tasks/rescue.yml
